# Site settings
title: Office of the Federal Chief Information Officer
email: ofcio@omb.eop.gov
description: > # this means to ignore newlines until "baseurl:"
#

baseurl: "https://policy.cio.gov" # the subpath of your site, e.g. /blog
url: "https://policy.cio.gov" # the base hostname & protocol for your site

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# Put the information about your site's GitHub repository if it is public
repo_url: https://github.com/ombegov/policy-v2

collections: 
  overview:
    output: true
    permalink: /:path/
    url: /
    status: home 
    title: Welcome
    github-label: home
  drafts_overview:
    output: true
    permalink: /drafts/:path/
    url: /drafts/
    status: draft
    title: Draft Policies
    github-label: draft policies
  finalized_overview:
    output: true
    permalink: /finalized/:path
    url: /finalized/
    status: finalized
    title: Finalized Policies
    github-label: finalized policies
  resources_overview:
    output: true
    permalink: /resources/:path/
    url: /resources/
    status: resource
    title: Agency Resources
    github-label: agency resources
  m-15-14-fitara:
    output: true
    permalink: /fitara/:path/
    url: /fitara/
    status: finalized
    title: "M-15-14: Management and Oversight of Federal Information Technology"
    github-label: fitara
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2015/m-15-14.pdf
  m-16-21-source-code:
    output: true
    permalink: /source-code/:path/
    url: /source-code/
    status: finalized
    title: "M-16-21: Federal Source Code Policy"
    github-label: source-code
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2016/m_16_21.pdf
  m-13-13-open-data:
    output: true
    permalink: /open-data/:path/
    url: /open-data/
    status: finalized
    title: "M-13-13: Open Data Policyâ€” Managing Information as an Asset"
    github-lavel: open-data
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2013/m-13-13.pdf  
  m-17-05-fisma-guidance-2017:
    output: true
    permalink: /fisma-guidance-2017/:path/
    url: /fisma-guidance-2017/
    status: finalized
    title: "M-17-05: Fiscal Year 2016-2017 Guidance on Federal Information Security and Privacy Management Requirements"
    github-label: fisma-guidance-2017
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2017/m-17-05.pdf
  fitara-resources:
    output: true
    permalink: /fitara-resources/:path/
    url: /fitara-resources/
    status: resource
    title: FITARA resources
    github-label: fitara
  draft-cyber-acquisitions:
    output: true
    permalink: /cybersecurity-protections-in-federal-acquisitions/:path/
    url: /cybersecurity-protections-in-federal-acquisitions/
    status: draft
    title: Improving Cybersecurity Protections in Federal Acquisitions
    github-label: cyber-acquisitions
  draft-it-modernization:
    output: true
    permalink: /it-modernization/:path/
    url: /it-modernization/
    status: draft
    title: Information Technology Modernization Initiative
    github-label: it-modernization
    download-link: https://github.com/ombegov/policy-v2/raw/gh-pages/assets/PDF/ITMF_Draft.pdf
  policy-schema:
    output: true
    permalink: /policy-schema/:path/
    url: /policy-schema/
    status: draft
    title: Policy Schema 
    github-label: policy-schema
  m-17-06-web-policy:
    output: true
    permalink: /web-policy/:path/
    url: /web-policy/
    status: finalized
    title: "M-17-06: Policies for Federal Agency Public Websites and Digital Services"
    github-label: _m-17-06-web-policy
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2017/m-17-06.pdf
  m-17-09-HVA:
    output: true
    permalink: /hva/:path/
    url: /hva/
    status: finalized
    title: "M-17-09: Management of Federal High Value Assets"
    github-label: _m-17-09-HVA
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2017/m-17-09.pdf
  m-16-19-dcoi:
    output: true
    permalink: /dcoi/:path/
    url: /dcoi/
    status: finalized
    title: "M-16-19: Data Center Optimization Initiative (DCOI)"
    github-label: _m-16-19-dcoi
    download-link: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2016/m_16_19_1.pdf
  m-17-15-rescissions-identity-management:
    output: true
    permalink: /rescissions-identity-management/:path/
    url: /rescissions-identity-management/
    status: finalized
    title: "M-17-15: Rescission of Memoranda Relating to Identity Management"
    github-label: _m-17-15
    download-link: https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2017/m-17-15.pdf
CYBERDRAFT:
    output: true
    permalink: /cyberdraft/:path/
    url: /cyberdraft/
    status: draft
    title: "CYBERDRAFT" 
    github-label: cyberdraft
    download-link:  
